# Site settings
title: ColoradoSpringsJS - Javascript User Group
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The official website of the Colorado Springs JavaScript User Group.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coloradospringsjs.org" # the base hostname & protocol for your site
github_username:  coloradoSpringsJS

# Build settings
markdown: kramdown
